### ISSUE TITLE
Notifications by email

### ISSUE THREAD

**Issue by samuraisam** [charge-beacon/charge-beacon#3]
This will depend on #2

**Comment by adamjohnson** [comment]
Email notifications would be a killer feature. I don't know of any other site that offers this functionality. It would be a great competitive advantage for Chage Beacon. 👍

**Comment by samuraisam** [comment]
@adamjohnson I just pushed a change which enables email notifications on saved searches. I'm testing it out now. If you'd like to test, please let me know if you run into any issues. Thanks!

**Comment by adamjohnson** [comment]
I just created a saved search with a daily wrap up email frequency. I will report back after a few days on how it's working.

One thing: when hitting "Save" to create or edit a search, there is no confirmation message. Eg: something like, "Thanks for updating your search. Your changes have been saved." That threw me for a loop—even though I recognized what was happening.

**Comment by samuraisam** [comment]
@adamjohnson good point, I added messages on search create/update/delete actions.

**Comment by samuraisam** [comment]
Deployed and merged!

**Comment by adamjohnson** [comment]
FWIW, I did not get an email from Charge Beacon. I did not spin up the app locally, only what's at chargebeacon.app. I'll let you know if that changes on 2/2/24.

**Comment by adamjohnson** [comment]
Just following up here: I have gotten a few emails from Charge Beacon. It appears to only email me when there is a change to the status of a charger. 

Upon reflection, this is preferred IMO. That said, when I originally set up the alert, I thought it was just going to send me a daily email—no matter if a status changed or not.

It might be beneficial to add a message that explains this. Eg: "Charge Beacon will check daily/weekly for status changes. It will only email you if there is a status change with a charger."

_______________

Side note: these emails are super cool. Fantastic feature. Thanks for implementing this!
